# Generated by Django 3.2.22 on 2023-12-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
